// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cosmic Secrets - Desvendando os Mistérios do Universo",
  description: "Blog especializado em astronomia, astrofísica e cosmologia. Descubra os segredos dos buracos negros, vida alienígena, exoplanetas e muito mais. Ebooks exclusivos sobre os mistérios do cosmos.",
  keywords: "astronomia, astrofísica, cosmologia, buracos negros, exoplanetas, vida alienígena, universo, ebooks astronomia",
  authors: [{ name: "Cosmic Secrets" }],
  openGraph: {
    title: "Cosmic Secrets - Desvendando os Mistérios do Universo",
    description: "Explore os mistérios mais profundos do cosmos com conteúdo científico de alta qualidade.",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}